//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MouseLiner.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MouseLiner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Icon App {
            get {
                object obj = ResourceManager.GetObject("App", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   色の選択(&amp;C)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChooseHorizontalLineColorMenuLabel {
            get {
                return ResourceManager.GetString("ChooseHorizontalLineColorMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   色の選択(&amp;C)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChooseVerticalLineColorMenuLabel {
            get {
                return ResourceManager.GetString("ChooseVerticalLineColorMenuLabel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon Disabled {
            get {
                object obj = ResourceManager.GetObject("Disabled", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon Enabled {
            get {
                object obj = ResourceManager.GetObject("Enabled", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   終了(&amp;X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExitMenuLabel {
            get {
                return ResourceManager.GetString("ExitMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ―(&amp;H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HorizontalLineMenuLabel {
            get {
                return ResourceManager.GetString("HorizontalLineMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中(&amp;M) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MediumLineWidthMenuLabel {
            get {
                return ResourceManager.GetString("MediumLineWidthMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   細い(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NarrowLineWidthMenuLabel {
            get {
                return ResourceManager.GetString("NarrowLineWidthMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   横線を表示(&amp;V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowHorizontalLineMenuLabel {
            get {
                return ResourceManager.GetString("ShowHorizontalLineMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   縦線を表示(&amp;V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowVerticalLineMenuLabel {
            get {
                return ResourceManager.GetString("ShowVerticalLineMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   太い(&amp;T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThickLineWidthMenuLabel {
            get {
                return ResourceManager.GetString("ThickLineWidthMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   半透明(&amp;T) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TransparentMenuLabel {
            get {
                return ResourceManager.GetString("TransparentMenuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ｜(&amp;V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string VerticalLineMenuLabel {
            get {
                return ResourceManager.GetString("VerticalLineMenuLabel", resourceCulture);
            }
        }
    }
}
